# Generated by Django 4.2.1 on 2023-10-11 20:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_owner_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a37ae608-715b-4c80-ae46-4ceab0cee41c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
