# Generated by Django 4.2.1 on 2023-10-11 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b24a53df-bd27-4d4c-b17e-5b49955d124f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
