# Generated by Django 4.2.1 on 2023-10-11 20:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3efceb97-ee32-4330-a280-4d385303c65b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
