# Generated by Django 4.2.1 on 2023-10-11 21:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('83f39293-7aa7-4fbf-bfeb-1bf8ecbe98e3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
